In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
titanic_train=pd.read_csv('https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv',
                           sep='\t')
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
titanic_train.tail(10)

PassengerId  Survived  Pclass  \
146          147         1       3   
147          148         0       3   
148          149         0       2   
149          150         0       2   
150          151         0       2   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                             Name     Sex   Age  SibSp  Parch  \
146  Andersson, Mr. August Edvard ("Wennerstrom")    male  27.0      0      0   
147              Ford, Miss. Robina Maggie "Ruby"  female   9.0      2      2   
148      Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5      0      2   
149             Byles, Rev. Thomas Roussel Davids    male  42.0      0      0   
150                    Bateman, Rev. Robert James    male  51.0      0      0   
151             Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1      0   
152                              Meo, Mr. Alfonzo    male  55.5      0      0   
153               van Billiard, Mr. Austin Blyler    male  40.5      0      2   
154                         Olsen, Mr. Ole Martin    male   NaN      0      0   
155                   Williams, Mr. Charles Duane    male  51.0      0      1   

          Ticket     Fare Cabin Embarked  
146       350043   7.7958   NaN        S  
147   W./C. 6608  34.3750   NaN        S  
148       230080  26.0000    F2        S  
149       244310  13.0000   NaN        S  
150  S.O.P. 1166  12.5250   NaN        S  
151       113776  66.6000    C2        S  
152   A.5. 11206   8.0500   NaN        S  
153     A/5. 851  14.5000   NaN        S  
154    Fa 265302   7.3125   NaN        S  
155     PC 17597  61.3792   NaN        C

In [4]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [5]:
#Chcking titanic_train.dtypes == "object"
titanic_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             30
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          125
Embarked         1
dtype: int64

In [6]:
#below code works for only numerical data
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [7]:
#Check for Categorical columns
titanic_train.dtypes[titanic_train.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [8]:
titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [9]:
#For Categorical data describe
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
a
titanic_train[a].describe()


Name   Sex  Ticket Cabin Embarked
count                       156   156     156    31      155
unique                      156     2     145    28        3
top     Moen, Mr. Sigurd Hansen  male  349909  C123        S
freq                          1   100       2     2      110

In [10]:
titanic_train[['Name','Sex','Age']].head()

Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [11]:
sorted(titanic_train["Name"])[1:15:2]# Check the first 15 sorted names

['Allen, Mr. William Henry',
 'Andersson, Miss. Erna Alexandra',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andrew, Mr. Edgardo Samuel',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Bateman, Rev. Robert James']

In [12]:
titanic_train[["Ticket"]][4:9] #Display from row 4 to 9t 

Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [13]:
titanic_train["Ticket"].describe()

count        156
unique       145
top       349909
freq           2
Name: Ticket, dtype: object

In [14]:
#Crate new columns
titanic_train['SibSp_Parch']=titanic_train['SibSp']+titanic_train['Parch']
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  SibSp_Parch  
0      0         A/5 21171   7.2500   NaN        S            1  
1      0          PC 17599  71.2833   C85        C            1  
2      0  STON/O2. 3101282   7.9250   NaN        S            0  
3      0            113803  53.1000  C123        S            1  
4      0            373450   8.0500   NaN        S            0

In [15]:
#Converting categorical into numerical
Embarked = pd.Categorical(titanic_train['Embarked'])
Embarked

[S, C, S, S, S, ..., S, S, S, S, C]
Length: 156
Categories (3, object): [C, Q, S]

In [16]:
titanic_train["Cabin"].unique()   # Check unique cabins

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [17]:
#Take the first letter of the column data
import numpy as np 
char_cabin = titanic_train["Cabin"].astype(str) # Convert data to str

new_Cabin = [cabin[0] for cabin in char_cabin] # Take first letter

new_Cabin = pd.Categorical(new_Cabin)

new_Cabin


[n, C, n, C, n, ..., C, n, n, n, n]
Length: 156
Categories (8, object): [A, B, C, D, E, F, G, n]

In [18]:
titanic_train["Cabin"] = new_Cabin
titanic_train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  SibSp_Parch  
0      0         A/5 21171   7.2500     n        S            1  
1      0          PC 17599  71.2833     C        C            1  
2      0  STON/O2. 3101282   7.9250     n        S            0  
3      0            113803  53.1000     C        S            1  
4      0            373450   8.0500     n        S            0  
5      0            330877   8.4583     n        Q            0  
6      0             17463  51.8625     E        S            0  
7      1            349909  21.0750     n        S            4  
8      2            347742  11.1333     n        S            2  
9      0            237736  30.0708     n        C            1

In [19]:
#Missing values with index wise
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [20]:
#checking maximum Fare in a dataset
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88], dtype=int64),)

In [21]:
titanic_train["Fare"][88]

263.0

In [22]:
titanic_train.iloc[np.where(titanic_train['Fare']==max(titanic_train['Fare']))]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
88           89         1       1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare Cabin Embarked  SibSp_Parch  
27  19.0      3      2  19950  263.0     C        S            5  
88  23.0      3      2  19950  263.0     C        S            5

In [23]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]
titanic_train["Family"].head()
most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family

(array([59, 71], dtype=int64),)

In [24]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]

most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family
titanic_train.iloc[most_family]

PassengerId  Survived  Pclass                                Name     Sex  \
59           60         0       3  Goodwin, Master. William Frederick    male   
71           72         0       3          Goodwin, Miss. Lillian Amy  female   

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked  SibSp_Parch  Family  
59  11.0      5      2  CA 2144  46.9     n        S            7       7  
71  16.0      5      2  CA 2144  46.9     n        S            7       7

##### Pandas Series

Docstring:     
One-dimensional ndarray with axis labels (including time series).

Labels need not be unique but must be a hashable type. The object
supports both integer- and label-based indexing and provides a host of
methods for performing operations involving the index. Statistical
methods from ndarray have been overridden to automatically exclude
missing data (currently represented as NaN).

Operations between Series (+, -, /, *, **) align values based on their
associated index values-- they need not be the same length. The result
index will be the sorted union of the two indexes.

In [25]:
import pandas as pd
import numpy as np

labels = ['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':10,'b':20,'c':30}

print('Labels: ' , labels)
print('MY data: ',my_data)
print('Dictionary: ',d)

pd.Series(data=my_data,index=labels)

Labels:  ['a', 'b', 'c']
MY data:  [10, 20, 30]
Dictionary:  {'a': 10, 'b': 20, 'c': 30}


a    10
b    20
c    30
dtype: int64

In [26]:
pd.Series(my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [27]:
arr

array([10, 20, 30])

In [28]:
print ("\nHolding numerical data\n",'-'*25, sep='')
pd.Series(arr)[1]


Holding numerical data
-------------------------


20

In [29]:
print ("\nHolding text labels\n",'-'*20, sep='')
pd.Series(labels)


Holding text labels
--------------------


0    a
1    b
2    c
dtype: object

In [30]:
print ("\nHolding text labels with customised index\n",'-'*40, sep='')
pd.Series(labels,index=['x','y','z'])


Holding text labels with customised index
----------------------------------------


x    a
y    b
z    c
dtype: object

In [31]:
d={'a':'ijkl' , 'b':20, 'c':30}
d.items

<function dict.items>

In [32]:
d={'a':'ijkl' , 'b':20, 'c':30}
#d.items
pd.DataFrame(d,index=['x','y','z']) #customised index insted of 0,1,2

a   b   c
x  ijkl  20  30
y  ijkl  20  30
z  ijkl  20  30

In [33]:
print ("\nHolding objects from a dictionary\n",'-'*40, sep='')
print(pd.Series([type, sum, max]))


Holding objects from a dictionary
----------------------------------------
0             <class 'type'>
1    <built-in function sum>
2    <built-in function max>
dtype: object


In [34]:
ser1 = pd.Series([1,2,3,4],index = [2,4,6,8])
ser2 = pd.Series([1,2,5,4],['CA', 'OR', 'NV', 'AZ'])
ser1

2    1
4    2
6    3
8    4
dtype: int64

In [35]:
ser1[8]

4

In [36]:
ser2[3]

4

In [37]:
ser2 

CA    1
OR    2
NV    5
AZ    4
dtype: int64

In [38]:
ser3=ser1+ser2
pd.DataFrame(ser3)

0
2  NaN
4  NaN
6  NaN
8  NaN
AZ NaN
CA NaN
NV NaN
OR NaN

In [39]:
print ("\nIndexing by number (positional value in the series)\n",'-'*52, sep='')
print("Value for CA in ser1:", ser1[2])
print("Value for AZ in ser1:", ser1[6])
print("Value for NV in ser2:", ser2[2])
ser1


Indexing by number (positional value in the series)
----------------------------------------------------
Value for CA in ser1: 1
Value for AZ in ser1: 3
Value for NV in ser2: 5


2    1
4    2
6    3
8    4
dtype: int64

In [40]:
print ("\nIndexing by a range\n",'-'*25, sep='')
print ("Value for OR, CO, and AZ in ser1:\n", ser1[0:3:2], sep='')


Indexing by a range
-------------------------
Value for OR, CO, and AZ in ser1:
2    1
6    3
dtype: int64


In [41]:
ser1 = pd.Series([1,2,3,4],['CA', 'OR', 'CO', 'CA'])
ser2 = pd.Series([1,2,5,4],['CA', 'NV', 'AZ','OR'])
ser3 = ser1+ser2
ser3

AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

In [42]:
print ("\nAfter adding the two series, the result looks like this...\n",'-'*59, sep='')
print(ser3)
print("\nPython tries to add values where it finds common index name, and puts NaN where indices are missing\n")


After adding the two series, the result looks like this...
-----------------------------------------------------------
AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

Python tries to add values where it finds common index name, and puts NaN where indices are missing



In [43]:
print ("\nThe idea works even for multiplication...\n",'-'*43, sep='')
print (ser1*ser2)


The idea works even for multiplication...
-------------------------------------------
AZ    NaN
CA    1.0
CA    4.0
CO    NaN
NV    NaN
OR    8.0
dtype: float64


In [44]:
import numpy as np
np.random.rand(1,10)  #Printing random 10 numbers in between 1 to 10

array([[0.79729039, 0.22635163, 0.72554099, 0.03854691, 0.17972363,
        0.91735108, 0.04655357, 0.27625856, 0.56678217, 0.30712758]])

In [45]:
from numpy.random import randn as rn
matrix_data = rn(5,4)   #print random 5*4 matrix
matrix_data

array([[-1.5135498 , -0.5666413 ,  0.64536062, -0.10213295],
       [ 0.52451312, -0.61529723,  0.78700242,  0.74818669],
       [ 0.55355649, -0.29645383,  0.57366714,  1.56547147],
       [ 0.23407906, -0.0889578 , -0.83320973,  0.67559484],
       [ 0.27140093, -0.17661843,  0.83623771, -0.44505965]])

In [46]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)   #print matrix 5*4
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']
df = pd.DataFrame(matrix_data,row_labels,column_headings)
#print("\nThe data frame looks like\n",'-'*45, sep='')
df

W         X         Y         Z
A  0.227280 -0.146451 -0.372463  1.977744
B -1.020025 -1.981721  0.052162 -1.872392
C -0.645363 -0.669044 -2.100770  1.096846
D  0.248590 -0.994366  2.256260 -0.886231
E -0.886236  0.615884  1.074040  0.518734

##### iloc = Purely integer-location based indexing for selection by position.

In [47]:
df.iloc[2]

W   -0.645363
X   -0.669044
Y   -2.100770
Z    1.096846
Name: C, dtype: float64

In [48]:
print("\nType of the pair of columns: ", type(df[['X','Z']]), sep='')
print ("\nSo, for more than one column, the object turns into a DataFrame")


Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>

So, for more than one column, the object turns into a DataFrame


In [49]:
print("\nThe 'X' column accessed by DOT method (NOT recommended)\n",'-'*55, sep='')
print(df['X'])


The 'X' column accessed by DOT method (NOT recommended)
-------------------------------------------------------
A   -0.146451
B   -1.981721
C   -0.669044
D   -0.994366
E    0.615884
Name: X, dtype: float64


In [50]:
type(df['X'])   #pandas series One Dimentional 

pandas.core.series.Series

In [51]:
type(df[['X']])   #pandas series two Dimentional 

pandas.core.frame.DataFrame

In [52]:
print("\nA column is created by assigning it in relation to an existing column\n",'-'*75, sep='')
df['New'] = df['X']+df['Z']
df['New (Sum of X and Z)'] = df['X']+df['Z']
print(df)


A column is created by assigning it in relation to an existing column
---------------------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
A  0.227280 -0.146451 -0.372463  1.977744  1.831293              1.831293
B -1.020025 -1.981721  0.052162 -1.872392 -3.854113             -3.854113
C -0.645363 -0.669044 -2.100770  1.096846  0.427803              0.427803
D  0.248590 -0.994366  2.256260 -0.886231 -1.880597             -1.880597
E -0.886236  0.615884  1.074040  0.518734  1.134617              1.134617


In [53]:
df

W         X         Y         Z       New  New (Sum of X and Z)
A  0.227280 -0.146451 -0.372463  1.977744  1.831293              1.831293
B -1.020025 -1.981721  0.052162 -1.872392 -3.854113             -3.854113
C -0.645363 -0.669044 -2.100770  1.096846  0.427803              0.427803
D  0.248590 -0.994366  2.256260 -0.886231 -1.880597             -1.880597
E -0.886236  0.615884  1.074040  0.518734  1.134617              1.134617

In [54]:
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep=' ')
df.drop("C",inplace=True,axis=0) # Notice the axis=1 option for columns, axis = 0 row for default, so one has to change it to 1
df


A column is dropped by using df.drop() method
 -------------------------------------------------------


W         X         Y         Z       New  New (Sum of X and Z)
A  0.227280 -0.146451 -0.372463  1.977744  1.831293              1.831293
B -1.020025 -1.981721  0.052162 -1.872392 -3.854113             -3.854113
D  0.248590 -0.994366  2.256260 -0.886231 -1.880597             -1.880597
E -0.886236  0.615884  1.074040  0.518734  1.134617              1.134617

In [55]:
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep=' ')
df.drop("Y",inplace=True,axis=1) # Notice the axis=1 option for columns, axis = 0 row for default, so one has to change it to 1
df


A column is dropped by using df.drop() method
 -------------------------------------------------------


W         X         Z       New  New (Sum of X and Z)
A  0.227280 -0.146451  1.977744  1.831293              1.831293
B -1.020025 -1.981721 -1.872392 -3.854113             -3.854113
D  0.248590 -0.994366 -0.886231 -1.880597             -1.880597
E -0.886236  0.615884  0.518734  1.134617              1.134617

In [56]:
df1=df.drop('A')
print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
print(df1)


A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------
          W         X         Z       New  New (Sum of X and Z)
B -1.020025 -1.981721 -1.872392 -3.854113             -3.854113
D  0.248590 -0.994366 -0.886231 -1.880597             -1.880597
E -0.886236  0.615884  0.518734  1.134617              1.134617


In [57]:
print("\nAn in-place change can be done by making inplace=True in the drop method\n",'-'*75, sep='')
df.drop('New (Sum of X and Z)', axis=1, inplace=True)
print(df)


An in-place change can be done by making inplace=True in the drop method
---------------------------------------------------------------------------
          W         X         Z       New
A  0.227280 -0.146451  1.977744  1.831293
B -1.020025 -1.981721 -1.872392 -3.854113
D  0.248590 -0.994366 -0.886231 -1.880597
E -0.886236  0.615884  0.518734  1.134617


### Selecting/indexing Rows

##### Label-based 'loc' method

##### Index (numeric) 'iloc' method

In [58]:
###### loc : Access a group of rows and columns by label(s) or a boolean array.

In [59]:
df

W         X         Z       New
A  0.227280 -0.146451  1.977744  1.831293
B -1.020025 -1.981721 -1.872392 -3.854113
D  0.248590 -0.994366 -0.886231 -1.880597
E -0.886236  0.615884  0.518734  1.134617

In [60]:
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.iloc[2])


Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

W      0.248590
X     -0.994366
Z     -0.886231
New   -1.880597
Name: D, dtype: float64


In [61]:
print("\nMultiple rows\n")
print(df.loc[['B','D']])


Multiple rows

          W         X         Z       New
B -1.020025 -1.981721 -1.872392 -3.854113
D  0.248590 -0.994366 -0.886231 -1.880597


In [62]:
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[2])


Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W      0.248590
X     -0.994366
Z     -0.886231
New   -1.880597
Name: D, dtype: float64


In [63]:
print("\nMultiple rows\n")
print(df.iloc[[1,2]])


Multiple rows

          W         X         Z       New
B -1.020025 -1.981721 -1.872392 -3.854113
D  0.248590 -0.994366 -0.886231 -1.880597


In [64]:
#### Subsetting DataFrame

In [65]:
matrix_data=rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings =['W','X','Y','Z']
df=pd.DataFrame(data=matrix_data,index=row_labels,columns=column_headings)
print("\nThe DatFrame\n",'-'*45, sep='')
print(df)


The DatFrame
---------------------------------------------
          W         X         Y         Z
A -0.105568 -2.032798  2.417243 -0.228775
B  0.275851  0.133823 -1.208135  0.157231
C  0.171225  1.878626 -1.155758  0.950158
D  1.758424  0.687874  1.443506 -0.712770
E  1.173472  1.754217 -0.496435  1.834532


In [66]:
print("\nElement at row 'B' and column 'Y' is\n") 
print(df.loc[['B','C'],['Y','W']])


Element at row 'B' and column 'Y' is

          Y         W
B -1.208135  0.275851
C -1.155758  0.171225


In [67]:
print("\nSubset comprising of rows B and D, and columns W and Y, is\n")
print(df.iloc[[1,2,3],[0,1]])


Subset comprising of rows B and D, and columns W and Y, is

          W         X
B  0.275851  0.133823
C  0.171225  1.878626
D  1.758424  0.687874


In [68]:
df.loc[['B','C']]

W         X         Y         Z
B  0.275851  0.133823 -1.208135  0.157231
C  0.171225  1.878626 -1.155758  0.950158

In [69]:
print("\nThe DataFrame\n",'-'*45, sep='')
print(df)


The DataFrame
---------------------------------------------
          W         X         Y         Z
A -0.105568 -2.032798  2.417243 -0.228775
B  0.275851  0.133823 -1.208135  0.157231
C  0.171225  1.878626 -1.155758  0.950158
D  1.758424  0.687874  1.443506 -0.712770
E  1.173472  1.754217 -0.496435  1.834532


In [70]:
print("\nBoolean DataFrame(s) where we are checking if the values are greater than 0\n",'-'*75, sep='')
print(df>0) #if it is greater than zero it print true


Boolean DataFrame(s) where we are checking if the values are greater than 0
---------------------------------------------------------------------------
       W      X      Y      Z
A  False  False   True  False
B   True   True  False   True
C   True   True  False   True
D   True   True   True  False
E   True   True  False   True


In [71]:
print(df.loc[['A','B','C']]>0)

       W      X      Y      Z
A  False  False   True  False
B   True   True  False   True
C   True   True  False   True


In [72]:
booldf = df>0
print("\nDataFrame indexed by boolean dataframe\n",'-'*45, sep='')
print(df[booldf])


DataFrame indexed by boolean dataframe
---------------------------------------------
          W         X         Y         Z
A       NaN       NaN  2.417243       NaN
B  0.275851  0.133823       NaN  0.157231
C  0.171225  1.878626       NaN  0.950158
D  1.758424  0.687874  1.443506       NaN
E  1.173472  1.754217       NaN  1.834532


In [73]:
import pandas as pd 
import numpy as np
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [74]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nA new DataFrame\n",'-'*25, sep='')
print(df)


A new DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [75]:
df[df['Height']>65] #print Height is above 65

Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [76]:
df['Height']>65

A     True
B     True
C    False
D     True
E    False
Name: Height, dtype: bool

In [77]:
booldf1 = df['Height']>65
booldf2 = df['Weight']>145

In [78]:
print("\nRows with Height > 65 inch and Weight >145 lbs\n",'-'*55, sep='')
print((booldf1) & (booldf2))


Rows with Height > 65 inch and Weight >145 lbs
-------------------------------------------------------
A    False
B     True
C    False
D     True
E    False
dtype: bool


In [79]:
print("\nDataFrame with only Age and Weight columns\n",'-'*68, sep='')
print(df[booldf1][['Age','Weight']])


DataFrame with only Age and Weight columns
--------------------------------------------------------------------
   Age  Weight
A   22     140
B   42     148
D   35     160


In [80]:
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
df=pd.DataFrame(data=matrix_data,index=row_labels,columns=column_headings)
print("\nThe DataFrame\n",'-'*25, sep='')
df


The DataFrame
-------------------------


Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [81]:
print("\nAfter resetting index\n",'-'*35, sep='')
print(df.reset_index())


After resetting index
-----------------------------------
  index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152


In [82]:
print("\nAfter resetting index with 'drop' option TRUE\n",'-'*45, sep='')
print(df.reset_index(drop=True))
"Student Teacher Engineer Doctor Nurse".split()


After resetting index with 'drop' option TRUE
---------------------------------------------
   Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152


['Student', 'Teacher', 'Engineer', 'Doctor', 'Nurse']

In [83]:
print("\nAdding a new column 'Profession'\n",'-'*45, sep='')
df['Profession']="Student Teacher Engineer Doctor Nurse".split()
df


Adding a new column 'Profession'
---------------------------------------------


Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse

In [84]:
print("\nSetting 'Profession' column as index\n",'-'*45, sep='')
df.set_index('Profession')


Setting 'Profession' column as index
---------------------------------------------


Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152

###### multi-indexing
# Index Levels

In [85]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index=list(zip(outside,inside))

In [86]:
print("\nTuple pairs after the zip and list command\n",'-'*45, sep='')
print(hier_index)


Tuple pairs after the zip and list command
---------------------------------------------
[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]


In [87]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
print("\nIndex hierarchy\n",'-'*25, sep='')
print(hier_index)


Index hierarchy
-------------------------
MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )


In [88]:
print("\nIndex hierarchy type\n",'-'*25, sep='')
print(type(hier_index))


Index hierarchy type
-------------------------
<class 'pandas.core.indexes.multi.MultiIndex'>


In [89]:
outside1 = ['G1','G1','G1','G2','G2','G2','X1','X2','X3','X4']
inside1 = [1,2,3,1,2,3,4,5]
hier_index1=list(zip(outside,inside))   #it will take only length of the list values

In [90]:
multi_in=pd.MultiIndex.from_tuples(hier_index1)
print(multi_in)

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )


In [91]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
print("\nCreating DataFrame with multi-index\n",'-'*37, sep='')
df1 = pd.DataFrame(data=np.round(rn(6,3)), index= hier_index, columns= ['A','B','C'])
df1


Creating DataFrame with multi-index
-------------------------------------


A    B    C
(G1, 1) -1.0  1.0 -1.0
(G1, 2) -1.0  1.0  4.0
(G1, 3)  2.0  2.0  2.0
(G2, 1)  1.0 -1.0 -1.0
(G2, 2) -0.0  0.0  1.0
(G2, 3)  0.0  0.0 -1.0

Pandas Series.xs() function return a cross-section from the Series/DataFrame for the given key value.

In [92]:
#cross tabulation like pivot table
print("\nGrabbing a cross-section from outer level\n",'-'*45, sep='')
print(df1.xs(('G1',2)))


Grabbing a cross-section from outer level
---------------------------------------------
A   -1.0
B    1.0
C    4.0
Name: (G1, 2), dtype: float64


In [93]:
#cross tabulation like pivot table
print("\nGrabbing a cross-section from outer level\n",'-'*45, sep='')
print(df1.xs(key=('G1',2)))


Grabbing a cross-section from outer level
---------------------------------------------
A   -1.0
B    1.0
C    4.0
Name: (G1, 2), dtype: float64


##### Pandas DataFrame.ix[ ]

Pandas DataFrame.ix[ ] is both Label and Integer based slicing technique. Besides pure label based and integer based, Pandas provides a hybrid method for selections and subsetting the object using the ix[] operator. ix[] is the most general indexer and will support any of the inputs in loc[] and iloc[].

In [94]:
# importing pandas and numpy 
import pandas as pd 
import numpy as np 
   
df = pd.DataFrame(np.random.randn(10, 4),columns = ['A', 'B', 'C', 'D']) 
  
print("Original DataFrame: \n" , df) 
   
# Integer slicing (printing all the rows of column 'A') 
print("\n After index slicing (On 'A'):") 
print("--------------------------") 
x = df.ix[:, 'A'] 
  
print(x) 

Original DataFrame: 
           A         B         C         D
0 -0.128093 -2.634054 -2.174559 -0.308637
1 -0.249027  0.045659  1.644653 -1.517433
2 -1.045871  3.450375 -0.103973 -0.305558
3 -0.927492  0.232106  0.586867 -0.660888
4 -1.092787  1.042303 -1.506590 -0.827596
5  2.224286  0.941945 -1.009951  0.430556
6  1.570151  0.002299 -0.316392 -0.300546
7 -0.755331 -0.573031  0.421775  0.782119
8  1.425904  0.854709 -1.192337  1.504685
9  1.814691 -1.886104  0.061975 -0.134690

 After index slicing (On 'A'):
--------------------------
0   -0.128093
1   -0.249027
2   -1.045871
3   -0.927492
4   -1.092787
5    2.224286
6    1.570151
7   -0.755331
8    1.425904
9    1.814691
Name: A, dtype: float64


C:\Users\arjun\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  if sys.path[0] == '':


In [95]:
# importing pandas and numpy 
import pandas as pd 
import numpy as np 
   
df = pd.DataFrame(np.random.randn(10, 4),columns = ['A', 'B', 'C', 'D']) 
  
print("Original DataFrame: \n" , df) 
   
# Integer slicing (printing all the rows of column 'A') 
print("\n After index slicing (On 'A'):") 
print("--------------------------") 
x = df.ix[:, 2] 
  
print(x)

Original DataFrame: 
           A         B         C         D
0 -0.741634  0.567070  1.876271  0.900273
1 -1.876613  2.232925 -1.051494  0.371704
2  0.052640  1.575177 -0.292130  0.424043
3  0.640600  1.014153 -0.822345  0.313521
4 -0.590156  0.562831  0.330054  1.220784
5  1.122301  0.494715  1.532209 -0.038685
6  0.383259  0.199086  0.564219  1.716687
7 -1.530957  0.006836  1.202697  0.097348
8  2.157845  0.089764  0.703594 -1.632973
9  2.400694  0.087185  0.820142  1.161374

 After index slicing (On 'A'):
--------------------------
0    1.876271
1   -1.051494
2   -0.292130
3   -0.822345
4    0.330054
5    1.532209
6    0.564219
7    1.202697
8    0.703594
9    0.820142
Name: C, dtype: float64


C:\Users\arjun\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  if sys.path[0] == '':
