In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
titanic_train=pd.read_csv('https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv',
                           sep='\t')
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
titanic_train.shape

(156, 12)

In [4]:
#print last 5 rows
titanic_train.tail(5)

PassengerId  Survived  Pclass                               Name     Sex  \
151          152         1       1  Pears, Mrs. Thomas (Edith Wearne)  female   
152          153         0       3                   Meo, Mr. Alfonzo    male   
153          154         0       3    van Billiard, Mr. Austin Blyler    male   
154          155         0       3              Olsen, Mr. Ole Martin    male   
155          156         0       1        Williams, Mr. Charles Duane    male   

      Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
151  22.0      1      0      113776  66.6000    C2        S  
152  55.5      0      0  A.5. 11206   8.0500   NaN        S  
153  40.5      0      2    A/5. 851  14.5000   NaN        S  
154   NaN      0      0   Fa 265302   7.3125   NaN        S  
155  51.0      0      1    PC 17597  61.3792   NaN        C

In [5]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
PassengerId    156 non-null int64
Survived       156 non-null int64
Pclass         156 non-null int64
Name           156 non-null object
Sex            156 non-null object
Age            126 non-null float64
SibSp          156 non-null int64
Parch          156 non-null int64
Ticket         156 non-null object
Fare           156 non-null float64
Cabin          31 non-null object
Embarked       155 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 14.8+ KB


In [7]:
#checking any missing values
titanic_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             30
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          125
Embarked         1
dtype: int64

In [8]:
#checking only categorical values
titanic_train.dtypes[titanic_train.dtypes=='object']

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [9]:
#below code works for only numerical data
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [10]:
#suppose if i want only mean and 50% columns data of the above descirbe values.
# lets convert transpose - change rows to columns and columns to rows
k=titanic_train.describe().transpose()
k

count       mean        std   min       25%      50%        75%  \
PassengerId  156.0  78.500000  45.177428  1.00  39.75000  78.5000  117.25000   
Survived     156.0   0.346154   0.477275  0.00   0.00000   0.0000    1.00000   
Pclass       156.0   2.423077   0.795459  1.00   2.00000   3.0000    3.00000   
Age          126.0  28.141508  14.613880  0.83  19.00000  26.0000   35.00000   
SibSp        156.0   0.615385   1.056235  0.00   0.00000   0.0000    1.00000   
Parch        156.0   0.397436   0.870146  0.00   0.00000   0.0000    0.00000   
Fare         156.0  28.109587  39.401047  6.75   8.00315  14.4542   30.37185   

               max  
PassengerId  156.0  
Survived       1.0  
Pclass         3.0  
Age           71.0  
SibSp          5.0  
Parch          5.0  
Fare         263.0

In [11]:
k.columns

Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='object')

In [12]:
k[['mean','50%']]

mean      50%
PassengerId  78.500000  78.5000
Survived      0.346154   0.0000
Pclass        2.423077   3.0000
Age          28.141508  26.0000
SibSp         0.615385   0.0000
Parch         0.397436   0.0000
Fare         28.109587  14.4542

In [13]:
#Check for Categorical columns
titanic_train.dtypes[titanic_train.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [14]:
titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [15]:
#For Categorical data describe
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
a
titanic_train[a].describe()

Name   Sex Ticket Cabin Embarked
count                     156   156    156    31      155
unique                    156     2    145    28        3
top     Olsen, Mr. Ole Martin  male   2651  C123        S
freq                        1   100      2     2      110

In [16]:
titanic_train[['Name','Sex','Age']].head()

Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [17]:
sorted(titanic_train["Name"])[1:15:2]# Check the first 15 sorted names alternativily

['Allen, Mr. William Henry',
 'Andersson, Miss. Erna Alexandra',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andrew, Mr. Edgardo Samuel',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Bateman, Rev. Robert James']

In [18]:
titanic_train[["Ticket"]][4:9] #Display from row 4 to 9

Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [19]:
titanic_train["Ticket"].describe()

count      156
unique     145
top       2651
freq         2
Name: Ticket, dtype: object

In [20]:
#combine two columns and create a new columns
titanic_train['SibSp_Parch']=titanic_train['SibSp']+titanic_train['Parch']
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  SibSp_Parch  
0      0         A/5 21171   7.2500   NaN        S            1  
1      0          PC 17599  71.2833   C85        C            1  
2      0  STON/O2. 3101282   7.9250   NaN        S            0  
3      0            113803  53.1000  C123        S            1  
4      0            373450   8.0500   NaN        S            0

In [21]:
#checking maximum value SibSp_Parch
titanic_train['SibSp_Parch'].max()

7

In [22]:
#suppose if we need titanic_train['SibSp_Parch'] value is maximum and age is above 38 passengers
sort=np.where(titanic_train['SibSp_Parch'].max() and titanic_train['Age']>38)
sort

(array([  6,  11,  13,  15,  30,  33,  35,  40,  52,  54,  62,  92,  94,
         96, 110, 116, 124, 129, 132, 149, 150, 152, 153, 155], dtype=int64),)

In [23]:
df1=titanic_train.loc[np.where(titanic_train['SibSp_Parch'].max() and titanic_train['Age']>38)]
print(df1.shape)
df1.head()

(24, 13)


PassengerId  Survived  Pclass                              Name     Sex  \
6             7         0       1           McCarthy, Mr. Timothy J    male   
11           12         1       1          Bonnell, Miss. Elizabeth  female   
13           14         0       3       Andersson, Mr. Anders Johan    male   
15           16         1       2  Hewlett, Mrs. (Mary D Kingcome)   female   
30           31         0       1          Uruchurtu, Don. Manuel E    male   

     Age  SibSp  Parch    Ticket     Fare Cabin Embarked  SibSp_Parch  
6   54.0      0      0     17463  51.8625   E46        S            0  
11  58.0      0      0    113783  26.5500  C103        S            0  
13  39.0      1      5    347082  31.2750   NaN        S            6  
15  55.0      0      0    248706  16.0000   NaN        S            0  
30  40.0      0      0  PC 17601  27.7208   NaN        C            0

In [24]:
titanic_train['Embarked'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked, dtype: object

In [25]:
titanic_train['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [26]:
#check only categorical values not NAN values in a column
Embarked = pd.Categorical(titanic_train['Embarked'])
Embarked

[S, C, S, S, S, ..., S, S, S, S, C]
Length: 156
Categories (3, object): [C, Q, S]

In [27]:
k=titanic_train["Cabin"].unique()   # Check unique cabins
k

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [28]:
print(k.shape)

(29,)


In [29]:
#suppose if i want to remove only nan values then
i=titanic_train['Cabin'].dropna()

In [30]:
i.unique()

array(['C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6', 'C23 C25 C27',
       'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33', 'F G73', 'E31',
       'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101', 'F E69', 'D47',
       'B86', 'F2', 'C2'], dtype=object)

In [31]:
i.shape

(31,)

In [32]:
titanic_train['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [33]:
#Take the first letter of the column data
import numpy as np 
char_cabin = titanic_train["Cabin"].astype(str) # Convert data to str

new_Cabin = [cabin[0] for cabin in char_cabin] # Take first letter

new_Cabin = pd.Categorical(new_Cabin)

new_Cabin


[n, C, n, C, n, ..., C, n, n, n, n]
Length: 156
Categories (8, object): [A, B, C, D, E, F, G, n]

In [34]:
titanic_train["Cabin"] = new_Cabin
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  SibSp_Parch  
0      0         A/5 21171   7.2500     n        S            1  
1      0          PC 17599  71.2833     C        C            1  
2      0  STON/O2. 3101282   7.9250     n        S            0  
3      0            113803  53.1000     C        S            1  
4      0            373450   8.0500     n        S            0

In [35]:
print(titanic_train.isnull().sum())
titanic_train.head()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            30
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin           0
Embarked        1
SibSp_Parch     0
dtype: int64


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  SibSp_Parch  
0      0         A/5 21171   7.2500     n        S            1  
1      0          PC 17599  71.2833     C        C            1  
2      0  STON/O2. 3101282   7.9250     n        S            0  
3      0            113803  53.1000     C        S            1  
4      0            373450   8.0500     n        S            0

In [36]:
#Missing values with index wise
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [37]:
#check null values of only Age column
age_null=titanic_train.loc[np.where(titanic_train['Age'].isnull()==True)]
print(age_null.shape)
age_null.head()

(30, 13)


PassengerId  Survived  Pclass                           Name     Sex  Age  \
5             6         0       3               Moran, Mr. James    male  NaN   
17           18         1       2   Williams, Mr. Charles Eugene    male  NaN   
19           20         1       3        Masselmani, Mrs. Fatima  female  NaN   
26           27         0       3        Emir, Mr. Farred Chehab    male  NaN   
28           29         1       3  O'Dwyer, Miss. Ellen "Nellie"  female  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  SibSp_Parch  
5       0      0  330877   8.4583     n        Q            0  
17      0      0  244373  13.0000     n        S            0  
19      0      0    2649   7.2250     n        C            0  
26      0      0    2631   7.2250     n        C            0  
28      0      0  330959   7.8792     n        Q            0

In [38]:
#check NAN values in either 'Age and 'Cabon column
i=titanic_train.loc[np.where(titanic_train['Age'].isnull()==True) or (np.where(titanic_train['Cabin'].isnull()==True)) or (np.where(titanic_train['Embarked'].isnull()==True))]
print(i.shape)
i.head()

(30, 13)


PassengerId  Survived  Pclass                           Name     Sex  Age  \
5             6         0       3               Moran, Mr. James    male  NaN   
17           18         1       2   Williams, Mr. Charles Eugene    male  NaN   
19           20         1       3        Masselmani, Mrs. Fatima  female  NaN   
26           27         0       3        Emir, Mr. Farred Chehab    male  NaN   
28           29         1       3  O'Dwyer, Miss. Ellen "Nellie"  female  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  SibSp_Parch  
5       0      0  330877   8.4583     n        Q            0  
17      0      0  244373  13.0000     n        S            0  
19      0      0    2649   7.2250     n        C            0  
26      0      0    2631   7.2250     n        C            0  
28      0      0  330959   7.8792     n        Q            0

In [39]:
#Suppose if we need nan values of 'Age,cabin and Embarked'
k= (np.where(titanic_train['Age'].isnull()==True) and np.where(titanic_train['Cabin'].isnull()==True) and np.where(titanic_train['Embarked'].isnull()==True))
k

(array([61], dtype=int64),)

In [40]:
df3=titanic_train.loc[k]
df3

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  \
61           62         1       1  Icard, Miss. Amelie  female  38.0      0   

    Parch  Ticket  Fare Cabin Embarked  SibSp_Parch  
61      0  113572  80.0     B      NaN            0

In [41]:
k= np.where(titanic_train['Age'].isnull() & titanic_train['Cabin'].isnull()  & titanic_train['Embarked'].isnull())
titanic_train.loc[k]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, SibSp_Parch]
Index: []

In [42]:
#From the above results NAN value is not available in Age,Cabin and Embarked in same row

In [43]:
# find missing values in Age,Cabin and 
df3=titanic_train.loc[k]
df3.head()

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, SibSp_Parch]
Index: []

In [44]:
df3=titanic_train.loc[np.where(titanic_train.isnull().sum())]
df3

PassengerId  Survived  Pclass                      Name     Sex   Age  \
5             6         0       3          Moran, Mr. James    male   NaN   
11           12         1       1  Bonnell, Miss. Elizabeth  female  58.0   

    SibSp  Parch  Ticket     Fare Cabin Embarked  SibSp_Parch  
5       0      0  330877   8.4583     n        Q            0  
11      0      0  113783  26.5500     C        S            0

In [45]:
np.where(titanic_train.isnull().sum())

(array([ 5, 11], dtype=int64),)

In [46]:
type(df3)

pandas.core.frame.DataFrame

In [47]:
#checking maximum Fare in a dataset
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88], dtype=int64),)

In [48]:
titanic_train["Fare"][88]

263.0

In [49]:
titanic_train.iloc[np.where(titanic_train['Fare']==max(titanic_train['Fare']))]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
88           89         1       1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare Cabin Embarked  SibSp_Parch  
27  19.0      3      2  19950  263.0     C        S            5  
88  23.0      3      2  19950  263.0     C        S            5

In [50]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  SibSp_Parch  
0      0         A/5 21171   7.2500     n        S            1  
1      0          PC 17599  71.2833     C        C            1  
2      0  STON/O2. 3101282   7.9250     n        S            0  
3      0            113803  53.1000     C        S            1  
4      0            373450   8.0500     n        S            0

In [51]:
#adding two numerical columns
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]
titanic_train["Family"].head()

0    1
1    1
2    0
3    1
4    0
Name: Family, dtype: int64

In [52]:
most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family

(array([59, 71], dtype=int64),)

In [53]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]

most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family
titanic_train.iloc[most_family]

PassengerId  Survived  Pclass                                Name     Sex  \
59           60         0       3  Goodwin, Master. William Frederick    male   
71           72         0       3          Goodwin, Miss. Lillian Amy  female   

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked  SibSp_Parch  Family  
59  11.0      5      2  CA 2144  46.9     n        S            7       7  
71  16.0      5      2  CA 2144  46.9     n        S            7       7

##### Pandas Series

Docstring:     
One-dimensional ndarray with axis labels (including time series).

Labels need not be unique but must be a hashable type. The object
supports both integer- and label-based indexing and provides a host of
methods for performing operations involving the index. Statistical
methods from ndarray have been overridden to automatically exclude
missing data (currently represented as NaN).

Operations between Series (+, -, /, *, **) align values based on their
associated index values-- they need not be the same length. The result
index will be the sorted union of the two indexes.

In [54]:
import pandas as pd
import numpy as np

labels = ['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':10,'b':20,'c':30}

print('Labels: ' , labels)
print('MY data: ',my_data)
print('Dictionary: ',d)

pd.Series(data=my_data,index=labels)

Labels:  ['a', 'b', 'c']
MY data:  [10, 20, 30]
Dictionary:  {'a': 10, 'b': 20, 'c': 30}


a    10
b    20
c    30
dtype: int64

In [55]:
pd.Series(my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [56]:
arr

array([10, 20, 30])

In [57]:
len(arr)

3

In [58]:
print ("\nHolding numerical data\n",'-'*25, sep='')
pd.Series(arr)[1]


Holding numerical data
-------------------------


20

In [59]:
print ("\nHolding text labels\n",'-'*20, sep='')
pd.Series(labels)


Holding text labels
--------------------


0    a
1    b
2    c
dtype: object

In [60]:
print ("\nHolding text labels with customised index\n",'-'*40, sep='')
pd.Series(labels,index=['x','y','z'])


Holding text labels with customised index
----------------------------------------


x    a
y    b
z    c
dtype: object

In [61]:
d={'a':'ABCD' , 'b':20, 'c':30}
d

{'a': 'ABCD', 'b': 20, 'c': 30}

In [62]:
d.keys

<function dict.keys>

In [63]:
type(d)

dict

In [64]:
d={'a':'ABCD' , 'b':20, 'c':30}
#d.items
pd.DataFrame(d,index=['x','y','z']) #customised index insted of 0,1,2

a   b   c
x  ABCD  20  30
y  ABCD  20  30
z  ABCD  20  30

In [65]:
print ("\nHolding objects from a dictionary\n",'-'*40, sep='')
print(pd.Series([type, sum, max]))


Holding objects from a dictionary
----------------------------------------
0             <class 'type'>
1    <built-in function sum>
2    <built-in function max>
dtype: object


In [66]:
ser1 = pd.Series(data=[1,2,3,4],index = [2,4,6,8])
ser2 = pd.Series([1,2,5,4],['CA', 'OR', 'NV', 'AZ'])
ser1

2    1
4    2
6    3
8    4
dtype: int64

In [67]:
ser1[8]

4

In [68]:
ser2[3]

4

In [69]:
ser2

CA    1
OR    2
NV    5
AZ    4
dtype: int64

In [70]:
ser3=ser1,ser2
ser3

(2    1
 4    2
 6    3
 8    4
 dtype: int64, CA    1
 OR    2
 NV    5
 AZ    4
 dtype: int64)

In [71]:
ser3=ser1+ser2  # Here non of the index values are matching together, so that it given NAN values
ser3

2    NaN
4    NaN
6    NaN
8    NaN
AZ   NaN
CA   NaN
NV   NaN
OR   NaN
dtype: float64

In [72]:
print ("\nIndexing by number (positional value in the series)\n",'-'*52, sep='')
print("Value for CA in ser1:", ser1[2])
print("Value for AZ in ser1:", ser1[6])
print("Value for NV in ser2:", ser2[2])
ser1


Indexing by number (positional value in the series)
----------------------------------------------------
Value for CA in ser1: 1
Value for AZ in ser1: 3
Value for NV in ser2: 5


2    1
4    2
6    3
8    4
dtype: int64

In [73]:
print ("\nIndexing by a range\n",'-'*25, sep='')
print ("Value for OR, CO, and AZ in ser1:\n", ser1[0:3:2], sep='')


Indexing by a range
-------------------------
Value for OR, CO, and AZ in ser1:
2    1
6    3
dtype: int64


In [74]:
ser1 = pd.Series([1,2,3,4],['CA', 'OR', 'CO', 'CA'])
ser2 = pd.Series([1,2,5,4],['CA', 'NV', 'AZ','OR'])
ser3 = (ser1+ser2)
ser3

AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

In [75]:
print ("\nAfter adding the two series, the result looks like this...\n",'-'*59, sep='')
print(ser3)
print("\nPython tries to add values where it finds common index name, and puts NaN where indices are missing\n")


After adding the two series, the result looks like this...
-----------------------------------------------------------
AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

Python tries to add values where it finds common index name, and puts NaN where indices are missing



In [76]:
print ("\nThe idea works even for multiplication...\n",'-'*43, sep='')
print (ser1*ser2)


The idea works even for multiplication...
-------------------------------------------
AZ    NaN
CA    1.0
CA    4.0
CO    NaN
NV    NaN
OR    8.0
dtype: float64


In [77]:
import numpy as np
np.random.rand(1,10)  #Printing random 10 numbers in between 1 to 10

array([[0.47326062, 0.74457402, 0.00984042, 0.24719149, 0.30518324,
        0.73321826, 0.08178539, 0.46680407, 0.57830592, 0.04742423]])

In [78]:
arr=np.random.rand(15).reshape(3,5)
arr

array([[0.66719368, 0.17003457, 0.17767705, 0.00324346, 0.52217159],
       [0.02605753, 0.54775997, 0.49349785, 0.0282765 , 0.14835972],
       [0.15265687, 0.7329638 , 0.03063695, 0.86130308, 0.97409151]])

In [79]:
arr1=pd.DataFrame(arr)
arr1

0         1         2         3         4
0  0.667194  0.170035  0.177677  0.003243  0.522172
1  0.026058  0.547760  0.493498  0.028277  0.148360
2  0.152657  0.732964  0.030637  0.861303  0.974092

In [80]:
arr1['Min_value']=arr1.min(axis=0)
arr1['Max_value']=arr1.max(axis=0)
arr1

0         1         2         3         4  Min_value  Max_value
0  0.667194  0.170035  0.177677  0.003243  0.522172   0.026058   0.667194
1  0.026058  0.547760  0.493498  0.028277  0.148360   0.170035   0.732964
2  0.152657  0.732964  0.030637  0.861303  0.974092   0.030637   0.493498

In [81]:
arr1.iloc[1]

0            0.026058
1            0.547760
2            0.493498
3            0.028277
4            0.148360
Min_value    0.170035
Max_value    0.732964
Name: 1, dtype: float64

In [82]:
from numpy.random import randn as rn
matrix_data = rn(5,4)   #print random 5*4 matrix
matrix_data

array([[-0.0728075 ,  1.15070642, -0.52121079, -0.912802  ],
       [ 0.75580983,  0.22806918, -0.42577139, -1.40882343],
       [-0.25083591, -0.20862201,  0.00727769, -0.24974346],
       [ 0.07310314,  0.94946604,  0.1607848 ,  1.5880578 ],
       [ 1.94703008, -0.13554547,  0.60104721, -1.40432312]])

In [83]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)   #print matrix 5*4
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']
df = pd.DataFrame(matrix_data,row_labels,column_headings)
print("\nThe data frame looks like\n",'-'*45, sep='')
df


The data frame looks like
---------------------------------------------


W         X         Y         Z
A  1.553601 -0.545043 -0.079292  0.583498
B  1.486946 -0.585262  0.635362  0.235064
C  0.848310 -0.029830 -0.355320 -0.646303
D  0.959314 -0.002379 -0.234328  1.595760
E  0.120444 -1.270945 -1.469080  0.010723

In [84]:
# if we need B&C row and X,Y column value
df.loc[['B','C']][['X','Y']]

X         Y
B -0.585262  0.635362
C -0.029830 -0.355320

##### iloc = Purely integer-location based indexing for selection by position.

In [85]:
df.iloc[2]

W    0.848310
X   -0.029830
Y   -0.355320
Z   -0.646303
Name: C, dtype: float64

In [86]:
print("\nType of the pair of columns: ", type(df[['X','Z']]), sep='')
print ("\nSo, for more than one column, the object turns into a DataFrame")


Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>

So, for more than one column, the object turns into a DataFrame


In [87]:
print("\nThe 'X' column accessed by DOT method (NOT recommended)\n",'-'*55, sep='')
print(df['X'])


The 'X' column accessed by DOT method (NOT recommended)
-------------------------------------------------------
A   -0.545043
B   -0.585262
C   -0.029830
D   -0.002379
E   -1.270945
Name: X, dtype: float64


In [88]:
type(df['X'])   #pandas series One Dimentional 

pandas.core.series.Series

In [89]:
type(df[['X']])   #pandas series two Dimentional 

pandas.core.frame.DataFrame

In [90]:
print("\nA column is created by assigning it in relation to an existing column\n",'-'*75, sep='')
df['New'] = df['X']+df['Z']
df['New (Sum of X and Z)'] = df['X']+df['Z']
print(df)


A column is created by assigning it in relation to an existing column
---------------------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
A  1.553601 -0.545043 -0.079292  0.583498  0.038455              0.038455
B  1.486946 -0.585262  0.635362  0.235064 -0.350197             -0.350197
C  0.848310 -0.029830 -0.355320 -0.646303 -0.676133             -0.676133
D  0.959314 -0.002379 -0.234328  1.595760  1.593380              1.593380
E  0.120444 -1.270945 -1.469080  0.010723 -1.260223             -1.260223


In [91]:
df

W         X         Y         Z       New  New (Sum of X and Z)
A  1.553601 -0.545043 -0.079292  0.583498  0.038455              0.038455
B  1.486946 -0.585262  0.635362  0.235064 -0.350197             -0.350197
C  0.848310 -0.029830 -0.355320 -0.646303 -0.676133             -0.676133
D  0.959314 -0.002379 -0.234328  1.595760  1.593380              1.593380
E  0.120444 -1.270945 -1.469080  0.010723 -1.260223             -1.260223

In [92]:
print("\nA row is dropped by using df.drop() method\n",'-'*55, sep=' ')
df.drop("C",inplace=True,axis=0) # Notice the axis=1 option for columns, axis = 0 row for default, so one has to change it to 1
df


A row is dropped by using df.drop() method
 -------------------------------------------------------


W         X         Y         Z       New  New (Sum of X and Z)
A  1.553601 -0.545043 -0.079292  0.583498  0.038455              0.038455
B  1.486946 -0.585262  0.635362  0.235064 -0.350197             -0.350197
D  0.959314 -0.002379 -0.234328  1.595760  1.593380              1.593380
E  0.120444 -1.270945 -1.469080  0.010723 -1.260223             -1.260223

In [93]:
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep=' ')
df.drop("Y",inplace=True,axis=1) # Notice the axis=1 option for columns, axis = 0 row for default, so one has to change it to 1
df


A column is dropped by using df.drop() method
 -------------------------------------------------------


W         X         Z       New  New (Sum of X and Z)
A  1.553601 -0.545043  0.583498  0.038455              0.038455
B  1.486946 -0.585262  0.235064 -0.350197             -0.350197
D  0.959314 -0.002379  1.595760  1.593380              1.593380
E  0.120444 -1.270945  0.010723 -1.260223             -1.260223

In [94]:
df1=df.drop('A')
print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
print(df1)


A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------
          W         X         Z       New  New (Sum of X and Z)
B  1.486946 -0.585262  0.235064 -0.350197             -0.350197
D  0.959314 -0.002379  1.595760  1.593380              1.593380
E  0.120444 -1.270945  0.010723 -1.260223             -1.260223


In [95]:
print("\nAn in-place change can be done by making inplace=True in the drop method\n",'-'*75, sep='')
df.drop('New (Sum of X and Z)', axis=1, inplace=True)
print(df)


An in-place change can be done by making inplace=True in the drop method
---------------------------------------------------------------------------
          W         X         Z       New
A  1.553601 -0.545043  0.583498  0.038455
B  1.486946 -0.585262  0.235064 -0.350197
D  0.959314 -0.002379  1.595760  1.593380
E  0.120444 -1.270945  0.010723 -1.260223


### Selecting/indexing Rows

##### Label-based 'loc' method

##### Index (numeric) 'iloc' method

In [96]:
###### loc : Access a group of rows and columns by label(s) or a boolean array.

In [97]:
df

W         X         Z       New
A  1.553601 -0.545043  0.583498  0.038455
B  1.486946 -0.585262  0.235064 -0.350197
D  0.959314 -0.002379  1.595760  1.593380
E  0.120444 -1.270945  0.010723 -1.260223

In [98]:
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.iloc[2])


Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

W      0.959314
X     -0.002379
Z      1.595760
New    1.593380
Name: D, dtype: float64


In [99]:
print("\nMultiple rows\n")
print(df.loc[['B','D']])


Multiple rows

          W         X         Z       New
B  1.486946 -0.585262  0.235064 -0.350197
D  0.959314 -0.002379  1.595760  1.593380


In [100]:
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[2])


Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W      0.959314
X     -0.002379
Z      1.595760
New    1.593380
Name: D, dtype: float64


In [101]:
print("\nMultiple rows\n")
print(df.iloc[[1,2]])


Multiple rows

          W         X         Z       New
B  1.486946 -0.585262  0.235064 -0.350197
D  0.959314 -0.002379  1.595760  1.593380


In [102]:
#### Subsetting DataFrame

In [103]:
matrix_data=rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings =['W','X','Y','Z']
df=pd.DataFrame(data=matrix_data,index=row_labels,columns=column_headings)
print("\nThe DatFrame\n",'-'*45, sep='')
print(df)


The DatFrame
---------------------------------------------
          W         X         Y         Z
A  0.764900 -0.044074  1.019573  1.177268
B -1.214018  0.252857  0.322462 -1.091389
C -0.141019 -0.889717 -0.732283 -0.359529
D  0.531523  0.284132  0.546609  0.174792
E -0.558429  0.994878 -0.929885  0.508340


In [104]:
#print(df.loc[['B','C'],['Y','W']])
df.loc['C']['Y']

-0.7322825960446746

In [105]:
print("\nElement at row 'B' and column 'Y' is\n") 
print(df.loc[['B','C'],['Y','W']])


Element at row 'B' and column 'Y' is

          Y         W
B  0.322462 -1.214018
C -0.732283 -0.141019


In [106]:
print("\nSubset comprising of rows B and D, and columns W and Y, is\n")
print(df.iloc[[1,2,3],[0,1]])


Subset comprising of rows B and D, and columns W and Y, is

          W         X
B -1.214018  0.252857
C -0.141019 -0.889717
D  0.531523  0.284132


In [107]:
df.loc[['B','C']]

W         X         Y         Z
B -1.214018  0.252857  0.322462 -1.091389
C -0.141019 -0.889717 -0.732283 -0.359529

In [108]:
print("\nThe DataFrame\n",'-'*45, sep='')
print(df)


The DataFrame
---------------------------------------------
          W         X         Y         Z
A  0.764900 -0.044074  1.019573  1.177268
B -1.214018  0.252857  0.322462 -1.091389
C -0.141019 -0.889717 -0.732283 -0.359529
D  0.531523  0.284132  0.546609  0.174792
E -0.558429  0.994878 -0.929885  0.508340


In [109]:
print("\nBoolean DataFrame(s) where we are checking if the values are greater than 0\n",'-'*75, sep='')
print(df>0) #if it is greater than zero it print true


Boolean DataFrame(s) where we are checking if the values are greater than 0
---------------------------------------------------------------------------
       W      X      Y      Z
A   True  False   True   True
B  False   True   True  False
C  False  False  False  False
D   True   True   True   True
E  False   True  False   True


In [110]:
print(df.loc[['A','B','C']]>0)

       W      X      Y      Z
A   True  False   True   True
B  False   True   True  False
C  False  False  False  False


In [117]:
booldf1 = df>0
print("\nDataFrame indexed by boolean dataframe\n",'-'*45, sep='')
print(df[booldf1])


DataFrame indexed by boolean dataframe
---------------------------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [118]:
import pandas as pd 
import numpy as np
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [119]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nA new DataFrame\n",'-'*25, sep='')
print(df)


A new DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [120]:
df[df['Height']>65] #print Height is above 65

Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [121]:
print("\nRows with Height > 65 inch and Weight >145 lbs\n",'-'*55, sep='')
df.loc[np.where(df['Height']>65) and (df['Weight']>145)]


Rows with Height > 65 inch and Weight >145 lbs
-------------------------------------------------------


Age  Height  Weight
B   42      70     148
D   35      68     160
E   25      62     152

In [122]:
print("\nDataFrame with only Age and Weight columns\n",'-'*68, sep='')
print(df[booldf1][['Age','Weight']])


DataFrame with only Age and Weight columns
--------------------------------------------------------------------
   Age  Weight
A   22     140
B   42     148
C   30     125
D   35     160
E   25     152


In [123]:
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
df=pd.DataFrame(data=matrix_data,index=row_labels,columns=column_headings)
print("\nThe DataFrame\n",'-'*25, sep='')
df


The DataFrame
-------------------------


Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [124]:
print("\nAfter resetting index\n",'-'*35, sep='')
print(df.reset_index())


After resetting index
-----------------------------------
  index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152


In [125]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [126]:
df1=df.reset_index()
df1

index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152

In [127]:
df1.index

RangeIndex(start=0, stop=5, step=1)

In [128]:
df1.iloc[2]

index       C
Age        30
Height     62
Weight    125
Name: 2, dtype: object

In [129]:
print("\nAfter resetting index with 'drop' option TRUE\n",'-'*45, sep='')
print(df.reset_index(drop=True))


After resetting index with 'drop' option TRUE
---------------------------------------------
   Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152


In [130]:
df

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [131]:
print("\nAdding a new column 'Profession'\n",'-'*45, sep='')
df['Profession']="Student Teacher Engineer Doctor Nurse".split()
df


Adding a new column 'Profession'
---------------------------------------------


Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse

In [132]:
print("\nSetting 'Profession' column as index\n",'-'*45, sep='')
df.set_index('Profession')


Setting 'Profession' column as index
---------------------------------------------


Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152

###### multi-indexing
# Index Levels

In [133]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index=list(zip(outside,inside))

In [134]:
print("\nTuple pairs after the zip and list command\n",'-'*45, sep='')
print(hier_index)


Tuple pairs after the zip and list command
---------------------------------------------
[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]


In [135]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
print("\nIndex hierarchy\n",'-'*25, sep='')
print(hier_index)


Index hierarchy
-------------------------
MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )


In [136]:
print("\nIndex hierarchy type\n",'-'*25, sep='')
print(type(hier_index))


Index hierarchy type
-------------------------
<class 'pandas.core.indexes.multi.MultiIndex'>


In [137]:
import pandas as pd
import numpy as np
from numpy.random import randn as rn

In [138]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]

In [139]:
mul_index=list(zip(outside,inside))
mul_index= pd.MultiIndex.from_tuples(mul_index)
mul_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [140]:
df1=pd.DataFrame(data=np.round(rn(6,3)),index=mul_index)
df1

0    1    2
G1 1 -0.0  1.0  0.0
   2  1.0 -1.0  1.0
   3 -1.0  1.0  1.0
G2 1  1.0  0.0  2.0
   2  1.0 -0.0 -0.0
   3  2.0  2.0  0.0

In [141]:
#Suppose if i need G1 of 3 row and second columns value
df1.loc['G1'][2][1]

0.0

In [142]:
import pandas as pd
import numpy as np
from numpy.random import randn as rn
print("\nCreating DataFrame with multi-index\n",'-'*37, sep='')
df2 = pd.DataFrame(data=np.round(rn(6,3)), index= hier_index, columns= ['A','B','C'])
df2


Creating DataFrame with multi-index
-------------------------------------


A    B    C
G1 1  1.0 -0.0  1.0
   2 -0.0  1.0 -0.0
   3  0.0 -1.0 -1.0
G2 1  0.0 -1.0 -1.0
   2  0.0  0.0 -2.0
   3  0.0  0.0  0.0

In [143]:
df2.index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [144]:
df2.xs(('G1',2))['B']

1.0

Pandas Series.xs() function return a cross-section from the Series/DataFrame for the given key value.

In [145]:
#cross tabulation like pivot table
print("\nGrabbing a cross-section from outer level\n",'-'*45, sep='')
print(df1.xs(('G1',2)))


Grabbing a cross-section from outer level
---------------------------------------------
0    1.0
1   -1.0
2    1.0
Name: (G1, 2), dtype: float64


In [146]:
#cross tabulation like pivot table
print("\nGrabbing a cross-section from outer level\n",'-'*45, sep='')
print(df1.xs(key=('G1',2)))


Grabbing a cross-section from outer level
---------------------------------------------
0    1.0
1   -1.0
2    1.0
Name: (G1, 2), dtype: float64


##### Pandas DataFrame.ix[ ]

Pandas DataFrame.ix[ ] is both Label and Integer based slicing technique. Besides pure label based and integer based, Pandas provides a hybrid method for selections and subsetting the object using the ix[] operator. ix[] is the most general indexer and will support any of the inputs in loc[] and iloc[].

In [147]:
# importing pandas and numpy 
import pandas as pd 
import numpy as np 
   
df = pd.DataFrame(np.random.randn(10, 4),columns = ['A', 'B', 'C', 'D']) 
  
print("Original DataFrame: \n" , df) 
   
# Integer slicing (printing all the rows of column 'A') 
print("\n After index slicing (On 'A'):") 
print("--------------------------") 
x = df.ix[:, 'A'] 
  
print(x) 

Original DataFrame: 
           A         B         C         D
0 -0.408191  0.148872 -0.105396 -1.024908
1  1.435600  0.703133  2.248604 -0.717367
2  1.315343  0.635850  0.329010  1.159519
3 -0.757614 -0.090314 -0.034878 -0.063898
4  0.008372  0.350687 -0.656070  0.762167
5  0.952668 -0.260671 -1.800965 -0.101468
6  0.438245  0.141992  0.035119 -0.798540
7  0.368858 -1.005407  1.838594 -0.908096
8  1.221895  1.156387 -0.365941 -0.419914
9 -0.081606  0.655806  1.523323 -0.564153

 After index slicing (On 'A'):
--------------------------
0   -0.408191
1    1.435600
2    1.315343
3   -0.757614
4    0.008372
5    0.952668
6    0.438245
7    0.368858
8    1.221895
9   -0.081606
Name: A, dtype: float64


C:\Users\arjun\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  if sys.path[0] == '':


In [148]:
# importing pandas and numpy 
import pandas as pd 
import numpy as np 
   
df = pd.DataFrame(np.random.randn(10, 4),columns = ['A', 'B', 'C', 'D']) 
  
print("Original DataFrame: \n" , df) 
   
# Integer slicing (printing all the rows of column 'A') 
print("\n After index slicing (On 'A'):") 
print("--------------------------") 
x = df.ix[:, 2] 
  
print(x)

Original DataFrame: 
           A         B         C         D
0  1.430606  1.400522  1.289690  0.904459
1  0.383040  0.056693  1.391739  1.266678
2  0.910617  0.567350  0.037726  0.516451
3  0.048022  0.586933  0.653437 -0.783340
4  1.532178 -0.180529 -2.938169  0.893865
5  1.174519  0.293491  0.222340  0.140081
6 -0.594475  0.002539 -0.658776 -0.095995
7  0.850991 -0.672223 -0.284848 -1.320812
8 -0.821999  1.343195 -0.262547 -1.021092
9 -1.810940 -0.837301 -1.709195 -0.612108

 After index slicing (On 'A'):
--------------------------
0    1.289690
1    1.391739
2    0.037726
3    0.653437
4   -2.938169
5    0.222340
6   -0.658776
7   -0.284848
8   -0.262547
9   -1.709195
Name: C, dtype: float64


C:\Users\arjun\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  if sys.path[0] == '':
